# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/design_1.bd
# Block Designs: The module: 'design_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_floating_point_0_0/design_1_floating_point_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_0 || ORIG_REF_NAME==design_1_floating_point_0_0} -quiet] -quiet

# IP: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_floating_point_1_0/design_1_floating_point_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_1_0 || ORIG_REF_NAME==design_1_floating_point_1_0} -quiet] -quiet

# IP: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_floating_point_0_1/design_1_floating_point_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_1 || ORIG_REF_NAME==design_1_floating_point_0_1} -quiet] -quiet

# IP: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_fixed_to_float_0/design_1_fixed_to_float_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fixed_to_float_0 || ORIG_REF_NAME==design_1_fixed_to_float_0} -quiet] -quiet

# IP: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_ooc.xdc

# XDC: C:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/design_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/design_1.bd
# Block Designs: The module: 'design_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_floating_point_0_0/design_1_floating_point_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_0 || ORIG_REF_NAME==design_1_floating_point_0_0} -quiet] -quiet

# IP: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_floating_point_1_0/design_1_floating_point_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_1_0 || ORIG_REF_NAME==design_1_floating_point_1_0} -quiet] -quiet

# IP: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_floating_point_0_1/design_1_floating_point_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_floating_point_0_1 || ORIG_REF_NAME==design_1_floating_point_0_1} -quiet] -quiet

# IP: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_fixed_to_float_0/design_1_fixed_to_float_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_fixed_to_float_0 || ORIG_REF_NAME==design_1_fixed_to_float_0} -quiet] -quiet

# IP: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0 || ORIG_REF_NAME==design_1_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/ip/design_1_clk_wiz_0/design_1_clk_wiz_0_ooc.xdc

# XDC: C:/Users/17073/Desktop/FPGA/FloatingPointOperator/FloatingPointMultiplication.srcs/sources_1/bd/design_1/design_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1'. Do not add the DONT_TOUCH constraint.
